config/routes.rb
Rails.application.routes.draw do
  resources :rentals do
    collection do
      post 'import'
    end
  end
  resources :leases do
    collection { post :import }
  end
  resources :sales
  resources :statuses
  resources :deductables
  resources :banks
  resources :originators
  resources :attorneys
  resources :agents do
    collection do
      post 'import'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'application#index'
end

app/views/layouts/shared/_header.html.slim
header#header
  #logo-group
    span#logo
      = image_tag 'logo.png', alt: 'Admin'

  #hide-menu.btn-header.pull-left
    span
      a href="javascript:;" data-action="toggleMenu" title="Collapse Menu"
        = icon('reorder')

  .project-context.hidden-xs
    span.label SITE:
    span.project-selector = current_tenant


  .pull-right
    #logout.btn-header.transparent.pull-right
      span
        = link_to icon('sign-out'), destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }

    form.header-search.pull-right
      input#search-fld type="text" name="param" placeholder="Quick Search"
      button type="submit" = icon('search')

    #fullscreen.btn-header.transparent.pull-right
      span
        a href="javascript:;" data-action="launchFullscreen" title="Full Screen" = icon('arrows-alt')

app/views/layouts/shared/_ribbon.html.slim
#ribbon
  ol.breadcrumb
    = render_breadcrumbs :tag => :li, :separator => ""
  span.ribbon-button-alignment.pull-right
    == yield :actions

app/views/layouts/shared/_sidebar.html.slim
aside#left-panel
  span.minifyme data-action="minifyMenu" = icon('arrow-circle-left hit')
  .login-info
    span
      = link_to 'javascript:;', id: 'show-shortcut', 'data-action': 'toggleShortcut' do
        = gravatar_img_tag current_user
        span = current_user&.email || "Guest"
    
  nav
    ul
      li = link_to root_path, title: 'Dashboard' do
        = icon('home fa-lg fa-fw')
        span.menu-item-parent = t('.dashboard')
      
      - if policy(Agent).show?
        li = link_to agents_path, title: Agent.model_name.human(count: 10) do
          = icon 'users fa-lg fa-fw'
          span.menu-item-parent = Agent.model_name.human(count: 10)
      
      - if policy(Lease).show?
        li = link_to leases_path, title: Lease.model_name.human(count: 10) do
          = icon 'file-text fa-lg fa-fw'
          span.menu-item-parent = Lease.model_name.human(count: 10)
        
      - if policy(Sale).show?
        li = link_to sales_path, title: Sale.model_name.human(count: 10) do
          = icon 'money fa-lg fa-fw'
          span.menu-item-parent = Sale.model_name.human(count: 10)

      - if policy(Rental).show?
        li = link_to rentals_path, title: Rental.model_name.human(count: 10) do
          = icon 'calendar-check-o fa-lg fa-fw'
          span.menu-item-parent = Rental.model_name.human(count: 10)

      li 
        = link_to '#', title: I18n.t('.settings') do
          = icon 'wrench fa-lg fa-fw'
          span.menu-item-parent = t('.settings')
        ul
          - if policy(Bank).show?
            li = link_to Bank.model_name.human(count: 10), banks_path
          - if policy(Attorney).show?
            li = link_to Attorney.model_name.human(count: 10), attorneys_path
          - if policy(Originator).show?
            li = link_to Originator.model_name.human(count: 10), originators_path
          - if policy(Deductable).show?
            li = link_to Deductable.model_name.human(count: 10), deductables_path
          - if policy(Status).show?
            li = link_to Status.model_name.human(count: 10), statuses_path