config/routes.rb
Rails.application.routes.draw do
  resources :rentals do
    collection do
      post 'import'
    end
  end
  resources :leases do
    collection { post :import }
  end
  resources :sales
  resources :statuses
  resources :deductables
  resources :banks
  resources :originators
  resources :attorneys
  resources :agents do
    collection do
      post 'import'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'application#index'
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  add_breadcrumb I18n.t('listing', entity: Status.model_name.human(count: 10)), :saved_index_path, except: :index

  # GET /statuses
  # GET /statuses.json
  def index
    add_breadcrumb I18n.t('listing', entity: Status.model_name.human(count: 10))
    @q = policy_scope(Status).ransack(params[:q])
    @statuses = @q.result.page(params[:page]).per(session[:default_per])
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    authorize @status
    add_breadcrumb @status.name
  end

  # GET /statuses/new
  def new
    @status = Status.new
    authorize @status
    add_breadcrumb I18n.t('creating', entity: Status.model_name.human)
  end

  # GET /statuses/1/edit
  def edit
    authorize @status
    add_breadcrumb @status.name, @status
    add_breadcrumb I18n.t('editing', entity: Status.model_name.human)
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)
    authorize @status
    respond_to do |format|
      if @status.save
        format.html { redirect_to (params[:save_and_new].present? ? new_status_path : @status), success: I18n.t('notices.created', entity: Status.model_name.human, id: @status.id) }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    authorize @status
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, success: I18n.t('notices.updated', entity: Status.model_name.human, title: @status.name) }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    authorize @status
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :nature, :can_edit, :color)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.slim
= bootstrap_form_for @status do |f|
  = f.text_field :name
  = f.text_field :nature
  = f.check_box :can_edit
  = f.text_field :color, class: 'colorpicker'
  = f.submit I18n.t('save'), class: 'btn btn-primary'
  - if @status.new_record?
    = f.submit I18n.t('save_and_new'), name: 'save_and_new', class: 'btn btn-info'

app/views/statuses/_search.html.slim
#filters.collapse 
  .padding-10
    = search_form_for @q do |f|
      .row
        .col-sm-3.form-group
          = f.label :name_eq
          = f.text_field :name_eq, class: 'form-control input-xs'
        .col-sm-3.form-group
          = f.label :nature_eq
          = f.text_field :nature_eq, class: 'form-control input-xs'
        .col-sm-3.form-group
          = f.label :can_edit_eq
          = f.check_box :can_edit_eq, class: 'form-control input-xs'
      = f.submit I18n.t('filter'), class: 'btn bg-color-magenta txt-color-white btn-xs'
      = link_to I18n.t('clear'), statuses_path, class: 'btn btn-xs btn-danger'

app/views/statuses/edit.html.slim
- content_for :title, I18n.t('editing', entity: Status.model_name.human)
== render 'form'

app/views/statuses/index.html.slim
= content_for :title, Status.model_name.human(count: 10)
= content_for :actions do
  = link_to(icon('plus', I18n.t('create')), new_status_path, class: 'btn btn-ribbon btn-success') if policy(Status).create?
#widget-grid
  #widget-table.jarviswidget data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false"
    header
      span.widget-icon = icon('table')
      h2 = Status.model_name.human(count: 10)
      .widget-toolbar
        = paginate @statuses
      .widget-toolbar
        = pager_per_select
      .widget-toolbar
        = page_entries_info @statuses
      .jarviswidget-ctrls
        a.button-icon class=('txt-color-red' if params[:q].present?) href="javascript:;" data-toggle="collapse" data-target="#filters" = icon('search')
    div
      .widget-body.no-padding
        == render 'search'
        .table-responsive
          table.table.table-striped.table-hover.table-condensed
            thead
              tr
                th = Status.human_attribute_name(:name)
                th = Status.human_attribute_name(:nature)
                th = Status.human_attribute_name(:can_edit)
                th
            tbody
              - @statuses.each do |status|
                tr
                  td = link_to status.name, status
                  td = status.nature
                  td = status.can_edit
                  td
                    = link_to(I18n.t('edit'), edit_status_path(status), class: 'btn btn-primary') if policy(status).update?
                    = link_to(I18n.t('delete'), status_path(status), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }) if policy(status).destroy?

app/views/statuses/new.html.slim
- content_for :title, I18n.t('creating', entity: Status.model_name.human(count: 10))
== render 'form'

app/views/statuses/show.html.slim
- content_for :title, I18n.t('showing', entity: Status.model_name.human(count: 10))
- content_for :actions do
  = link_to I18n.t('edit'), edit_status_path(@status), class: 'btn btn-ribbon btn-primary'

p
  strong Name:
  = @status.name
p
  strong Nature:
  = @status.nature
p
  strong Can edit:
  = @status.can_edit