config/routes.rb
Rails.application.routes.draw do
  resources :rentals do
    collection do
      post 'import'
    end
  end
  resources :leases do
    collection { post :import }
  end
  resources :sales
  resources :statuses
  resources :deductables
  resources :banks
  resources :originators
  resources :attorneys
  resources :agents do
    collection do
      post 'import'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'application#index'
end

app/models/originator.rb
# == Schema Information
#
# Table name: originators
#
#  id         :integer          not null, primary key
#  name       :string
#  telephone  :string
#  email      :string
#  preferred  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Originator < ApplicationRecord
  default_scope { Customer.current_id ? where(customer: Customer.current_id) : all }
end

app/controllers/originators_controller.rb
class OriginatorsController < ApplicationController
  before_action :set_originator, only: [:show, :edit, :update, :destroy]

  add_breadcrumb I18n.t('listing', entity: Originator.model_name.human(count: 10)), :saved_index_path, except: :index

  # GET /originators
  # GET /originators.json
  def index
    add_breadcrumb I18n.t('listing', entity: Originator.model_name.human(count: 10))
    @q = policy_scope(Originator).ransack(params[:q])
    @originators = @q.result.page(params[:page]).per(session[:default_per])
  end

  # GET /originators/1
  # GET /originators/1.json
  def show
    authorize @originator
    add_breadcrumb @originator.name
  end

  # GET /originators/new
  def new
    @originator = Originator.new
    authorize @originator
    add_breadcrumb I18n.t('creating', entity: Originator.model_name.human)
  end

  # GET /originators/1/edit
  def edit
    authorize @originator
    add_breadcrumb @originator.name, @originator
    add_breadcrumb I18n.t('editing', entity: Originator.model_name.human)
  end

  # POST /originators
  # POST /originators.json
  def create
    @originator = Originator.new(originator_params)
    authorize @originator
    respond_to do |format|
      if @originator.save
        format.html { redirect_to (params[:save_and_new].present? ? new_originator_path : @originator), success: I18n.t('notices.created', entity: Originator.model_name.human, id: @originator.id) }
        format.json { render :show, status: :created, location: @originator }
      else
        format.html { render :new }
        format.json { render json: @originator.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /originators/1
  # PATCH/PUT /originators/1.json
  def update
    authorize @originator
    respond_to do |format|
      if @originator.update(originator_params)
        format.html { redirect_to @originator, success: I18n.t('notices.updated', entity: Originator.model_name.human, title: @originator.name) }
        format.json { render :show, status: :ok, location: @originator }
      else
        format.html { render :edit }
        format.json { render json: @originator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /originators/1
  # DELETE /originators/1.json
  def destroy
    authorize @originator
    @originator.destroy
    respond_to do |format|
      format.html { redirect_to originators_url, notice: 'Originator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_originator
      @originator = Originator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def originator_params
      params.require(:originator).permit(:name, :telephone, :email, :preferred)
    end
end

app/helpers/originators_helper.rb
module OriginatorsHelper
end

app/views/originators/_form.html.slim
= bootstrap_form_for @originator do |f|
  = f.text_field :name
  = f.text_field :telephone
  = f.text_field :email
  = f.check_box :preferred
  = f.submit I18n.t('save'), class: 'btn btn-primary'
  - if @originator.new_record?
    = f.submit I18n.t('save_and_new'), name: 'save_and_new', class: 'btn btn-info'

app/views/originators/_search.html.slim
#filters.collapse 
  .padding-10
    = search_form_for @q do |f|
      .row
        .col-sm-3.form-group
          = f.label :name_eq
          = f.text_field :name_eq, class: 'form-control input-xs'
        .col-sm-3.form-group
          = f.label :telephone_eq
          = f.text_field :telephone_eq, class: 'form-control input-xs'
        .col-sm-3.form-group
          = f.label :email_eq
          = f.text_field :email_eq, class: 'form-control input-xs'
        .col-sm-3.form-group
          = f.label :preferred_eq
          = f.check_box :preferred_eq, class: 'form-control input-xs'
      = f.submit I18n.t('filter'), class: 'btn bg-color-magenta txt-color-white btn-xs'
      = link_to I18n.t('clear'), originators_path, class: 'btn btn-xs btn-danger'

app/views/originators/edit.html.slim
- content_for :title, I18n.t('editing', entity: Originator.model_name.human)
== render 'form'

app/views/originators/index.html.slim
= content_for :title, Originator.model_name.human(count: 10)
= content_for :actions do
  = link_to(icon('plus', I18n.t('create')), new_originator_path, class: 'btn btn-ribbon btn-success') if policy(Originator).create?
#widget-grid
  #widget-table.jarviswidget data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false"
    header
      span.widget-icon = icon('table')
      h2 = Originator.model_name.human(count: 10)
      .widget-toolbar
        = paginate @originators
      .widget-toolbar
        = pager_per_select
      .widget-toolbar
        = page_entries_info @originators
      .jarviswidget-ctrls
        a.button-icon class=('txt-color-red' if params[:q].present?) href="javascript:;" data-toggle="collapse" data-target="#filters" = icon('search')
    div
      .widget-body.no-padding
        == render 'search'
        .table-responsive
          table.table.table-striped.table-hover.table-condensed
            thead
              tr
                th = Originator.human_attribute_name(:name)
                th = Originator.human_attribute_name(:telephone)
                th = Originator.human_attribute_name(:email)
                th = Originator.human_attribute_name(:preferred)
                th
            tbody
              - @originators.each do |originator|
                tr
                  td = link_to originator.name, originator
                  td = originator.telephone
                  td = originator.email
                  td = originator.preferred
                  td
                    = link_to(I18n.t('edit'), edit_originator_path(originator), class: 'btn btn-primary') if policy(originator).update?
                    = link_to(I18n.t('delete'), originator_path(originator), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }) if policy(originator).destroy?

app/views/originators/new.html.slim
- content_for :title, I18n.t('creating', entity: Originator.model_name.human(count: 10))
== render 'form'

app/views/originators/show.html.slim
- content_for :title, I18n.t('showing', entity: Originator.model_name.human(count: 10))
- content_for :actions do
  = link_to I18n.t('edit'), edit_originator_path(@originator), class: 'btn btn-ribbon btn-primary'

p
  strong Name:
  = @originator.name
p
  strong Telephone:
  = @originator.telephone
p
  strong Email:
  = @originator.email
p
  strong Preferred:
  = @originator.preferred