config/routes.rb
Rails.application.routes.draw do
  resources :rentals do
    collection do
      post 'import'
    end
  end
  resources :leases do
    collection { post :import }
  end
  resources :sales
  resources :statuses
  resources :deductables
  resources :banks
  resources :originators
  resources :attorneys
  resources :agents do
    collection do
      post 'import'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'application#index'
end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id                :integer          not null, primary key
#  reference         :string
#  seller_id         :integer
#  buyer_id          :integer
#  contract_start_on :date
#  purchase_price    :decimal(14, 2)
#  deposit_amount    :decimal(14, 2)
#  deposit_due_on    :date
#  attorney_id       :integer
#  bond_attorney_id  :integer
#  bond_due_on       :date
#  originator_id     :integer
#  status_id         :integer
#  registered_on     :date
#  bank_id           :integer
#  grant_amount      :decimal(14, 2)
#  commission_amount :decimal(14, 2)
#  tax_amount        :decimal(14, 2)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Sale < ApplicationRecord
  belongs_to :seller, class_name: 'Contact'
  accepts_nested_attributes_for :seller
  belongs_to :buyer, class_name: 'Contact'
  accepts_nested_attributes_for :buyer
  belongs_to :attorney
  belongs_to :bond_attorney, class_name: 'Attorney'
  belongs_to :originator
  belongs_to :status
  belongs_to :bank

  has_one :address, as: :addressable
  accepts_nested_attributes_for :address

  has_many :commissions, as: :commissionable
  accepts_nested_attributes_for :commissions, allow_destroy: true

  validates :reference,
    :contract_start_on,
    :purchase_price,
    :deposit_amount,
    :status_id,
    :attorney_id,
    :originator_id,
    :commission_amount,
    presence: true

  default_scope { Customer.current_id ? where(customer: Customer.current_id) : all }

  before_save do
    self.tax_amount = self.commission_amount - (self.commission_amount / 1.14)
  end

  def nett_commission_amount
    commission_amount - tax_amount
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  add_breadcrumb I18n.t('listing', entity: Sale.model_name.human(count: 10)), :saved_index_path, except: :index

  # GET /sales
  # GET /sales.json
  def index
    add_breadcrumb I18n.t('listing', entity: Sale.model_name.human(count: 10))
    @q = policy_scope(Sale).ransack(params[:q])
    @sales = @q.result.includes(:buyer).includes(:seller).includes(:attorney).includes(:bond_attorney).page(params[:page]).per(session[:default_per])
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    authorize @sale
    add_breadcrumb @sale.reference
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    authorize @sale
    @sale.build_address
    @sale.build_buyer
    @sale.build_seller
    add_breadcrumb I18n.t('creating', entity: Sale.model_name.human)
  end

  # GET /sales/1/edit
  def edit
    authorize @sale
    add_breadcrumb @sale.reference, @sale
    add_breadcrumb I18n.t('editing', entity: Sale.model_name.human)
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    authorize @sale
    respond_to do |format|
      if @sale.save
        format.html { redirect_to (params[:save_and_new].present? ? new_sale_path : @sale), success: I18n.t('notices.created', entity: Sale.model_name.human, id: @sale.id) }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    authorize @sale
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, success: I18n.t('notices.updated', entity: Sale.model_name.human, title: @sale.reference) }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    authorize @sale
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:reference, :seller_id, :buyer_id, :contract_start_on, :purchase_price, :deposit_amount, :deposit_due_on, :attorney_id, :bond_attorney_id, :bond_due_on, :originator_id, :status_id, :registered_on, :bank_id, :grant_amount, :commission_amount, :seller_attributes => [:id, :first_name, :last_name, :email, :mobile, :company], :buyer_attributes => [:id, :first_name, :last_name, :email, :mobile, :company], :address_attributes => [:id, :erf, :street_number, :street_name, :unit, :complex, :suburb, :city, :post_code], :commissions_attributes => [:id, :agent_id, :agent_percent, :_destroy, :deductions_attributes => [:id, :deductable_id, :name, :total_amount]])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_address_fields.html.slim
= widget title, 'home' do
  .row
    .col-md-6
      = f.text_field :erf
    .col-md-6
      = f.text_field :street_number
  .row
    .col-md-4
      = f.text_field :unit
    .col-md-8
      = f.text_field :complex

  = f.text_field :street_name
  = f.text_field :suburb
  = f.text_field :city
  = f.text_field :post_code

app/views/sales/_commission_fields.html.slim
= widget title, 'money', data: { behavior: 'commission' } do
  = f.collection_select :agent_id, Agent.all, :id, :full_name, { include_blank: true }, data: { behavior: 'agent_id'}
  = f.text_field :agent_percent, 'data-behavior': :agent_percent
  = f.text_field :commission_amount, readonly: true, 'data-behavior': :agent_comm_gross
  = f.text_field :tax_percent, readonly: true, 'data-behavior': :agent_tax_percent 
  = f.text_field :tax_amount, readonly: true, 'data-behavior': :agent_tax_amount
  .form-group
    label = Commission.human_attribute_name :nett_commission_amount
    = text_field_tag :nett_commission_amount, nil, readonly: true, class: 'form-control', data: { behavior: 'agent_nett_comm' }

  = f.fields_for :deductions do |builder|
    = render 'deduction_fields', f: builder
  = link_to_add_fields t('.add_fields'), f, :deductions 
  = f.hidden_field :_destroy
  = link_to t('remove'), '#', class: 'btn btn-danger', data: { behavior: 'remove_fields' }

app/views/sales/_contact_fields.html.slim
= widget title, 'user' do
  = f.text_field :first_name
  = f.text_field :last_name
  = f.text_field :mobile
  = f.text_field :company

app/views/sales/_deduction_fields.html.slim
.jarviswidget
  div
    .widget-body
      = f.collection_select :deductable_id, Deductable.all, :id, :name, { include_blank: true }, data: { behavior: 'deductable_id' }
      = f.text_field :name, data: { behavior: 'name' }
      = f.text_field :total_amount, data: { behavior: 'total_cost' }
      = f.hidden_field :_destroy
      = link_to t('remove'), '#', class: 'btn btn-danger', data: { behavior: 'remove_fields' }

app/views/sales/_form.html.slim
= bootstrap_form_for @sale do |f|
  .row
    .col-sm-3
      = widget Sale.model_name.human, 'money' do
        = f.text_field :reference
        = f.text_field :contract_start_on, append: icon('calendar'), class: 'datepicker', 'data-dateformat': 'yy-mm-dd'
        = f.text_field :purchase_price
        = f.text_field :deposit_amount
        = f.text_field :deposit_due_on, append: icon('calendar'), class: 'datepicker', 'data-dateformat': 'yy-mm-dd'
        = f.collection_select :status_id, Status.all, :id, :name
      = f.fields_for :seller do |builder|
        = render 'contact_fields', title: Sale.human_attribute_name(:seller), f: builder
    .col-sm-3
      = f.fields_for :address do |builder|
        = render 'address_fields', title: Address.model_name.human, f: builder
      = f.fields_for :buyer do |builder|
        = render 'contact_fields', title: Sale.human_attribute_name(:buyer), f: builder
    .col-sm-3
      = widget Sale.model_name.human, 'money' do
        = f.collection_select :attorney_id, Attorney.all, :id, :name
        = f.collection_select :bond_attorney_id, Attorney.all, :id, :name
        = f.text_field :bond_due_on, append: icon('calendar'), class: 'datepicker', 'data-dateformat': 'yy-mm-dd'
        = f.collection_select :originator_id, Originator.all, :id, :name
        = f.text_field :registered_on, append: icon('calendar'), class: 'datepicker', 'data-dateformat': 'yy-mm-dd'
        = f.collection_select :bank_id, Bank.all, :id, :name
        = f.text_field :grant_amount
    .col-sm-3
      = widget Sale.model_name.human, 'money' do
        = f.text_field :commission_amount
        = f.text_field :tax_amount, readonly: true

        .form-group
          label = Commission.human_attribute_name :nett_commission_amount
          = text_field_tag :sale_nett_amount, nil, readonly: true, class: 'form-control'
        .text-right
          = link_to_add_fields t('.add_fields'), f, :commissions

      = f.fields_for :commissions do |builder|
        = render 'commission_fields', f: builder, title: Sale.human_attribute_name(:commissions)
      
      
      = f.submit I18n.t('save'), class: 'btn btn-primary'
      - if @sale.new_record?
        = f.submit I18n.t('save_and_new'), name: 'save_and_new', class: 'btn btn-info'

app/views/sales/_search.html.slim
#filters.collapse 
  .padding-10
    = search_form_for @q do |f|
      .row
        .col-sm-3.form-group
          = f.label :reference_eq
          = f.text_field :reference_eq, class: 'form-control input-xs'
        .col-sm-3.form-group
          = f.label :status_id_eq
          = f.collection_select :status_id_eq, Status.all, :id, :name, { include_blank: true }, class: 'form-control input-xs'
      = f.submit I18n.t('filter'), class: 'btn bg-color-magenta txt-color-white btn-xs'
      = link_to I18n.t('clear'), sales_path, class: 'btn btn-xs btn-danger'

app/views/sales/edit.html.slim
- content_for :title, I18n.t('editing', entity: Sale.model_name.human)
== render 'form'

app/views/sales/index.html.slim
= content_for :title, Sale.model_name.human(count: 10)
= content_for :actions do
  = link_to(icon('plus', I18n.t('create')), new_sale_path, class: 'btn btn-ribbon btn-success') if policy(Sale).create?
#widget-grid
  #widget-table.jarviswidget data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false"
    header
      span.widget-icon = icon('table')
      h2 = Sale.model_name.human(count: 10)
      .widget-toolbar
        = paginate @sales
      .widget-toolbar
        = pager_per_select
      .widget-toolbar
        = page_entries_info @sales
      .jarviswidget-ctrls
        a.button-icon class=('txt-color-red' if params[:q].present?) href="javascript:;" data-toggle="collapse" data-target="#filters" = icon('search')
    div
      .widget-body.no-padding
        == render 'search'
        .table-responsive
          table.table.table-striped.table-hover.table-condensed
            thead
              tr
                th = Sale.human_attribute_name(:reference)
                th = Sale.human_attribute_name(:contract_start_on)
                th = Sale.human_attribute_name(:seller)
                th = Sale.human_attribute_name(:buyer)
                th = Sale.human_attribute_name(:purchase_price)
                th = Sale.human_attribute_name(:agent)
                th = Sale.human_attribute_name(:originator)
                th = Sale.human_attribute_name(:attorney)
                th = Sale.human_attribute_name(:bond_attorney)
                th = Sale.human_attribute_name(:status)
                th = Sale.human_attribute_name(:updated_at)
                th = Sale.human_attribute_name(:registered_on)
                th = Sale.human_attribute_name(:comments)
                th = Sale.human_attribute_name(:commission_amount)
                th
            tbody
              - @sales.each do |sale|
                tr style="background-color:#{sale.status.color}"
                  td = link_to sale.reference, sale
                  td = sale.contract_start_on
                  td = sale.seller&.name
                  td = sale.buyer&.name
                  td = number_to_currency(sale.purchase_price, unit: "R", separator: ".", delimiter: " ")
                  td = sale.commissions.collect { |c| c.agent.full_name }.join(",")
                  td = sale.originator&.name
                  td = sale.attorney&.name
                  td = sale.bond_attorney&.name
                  td = sale.status&.name
                  td = sale.updated_at.strftime("%B %d, %Y")
                  td = sale.registered_on
                  td = sale.comments
                  td = sale.commission_amount
                  td
                    = link_to(I18n.t('edit'), edit_sale_path(sale), class: 'btn btn-primary') if policy(sale).update?
                    = link_to(I18n.t('delete'), sale_path(sale), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }) if policy(sale).destroy?

app/views/sales/new.html.slim
- content_for :title, I18n.t('creating', entity: Sale.model_name.human(count: 10))
== render 'form'

app/views/sales/show.html.slim
- content_for :title, I18n.t('showing', entity: Sale.model_name.human(count: 10))
- content_for :actions do
  = link_to I18n.t('edit'), edit_sale_path(@sale), class: 'btn btn-ribbon btn-primary'

p
  strong Reference:
  = @sale.reference
p
  strong Seller:
  = @sale.seller
p
  strong Buyer:
  = @sale.buyer
p
  strong Contract start on:
  = @sale.contract_start_on
p
  strong Purchase price:
  = @sale.purchase_price
p
  strong Deposit amount:
  = @sale.deposit_amount
p
  strong Deposit due on:
  = @sale.deposit_due_on
p
  strong Attorney:
  = @sale.attorney
p
  strong Bond attorney:
  = @sale.bond_attorney
p
  strong Bond due on:
  = @sale.bond_due_on
p
  strong Originator:
  = @sale.originator
p
  strong Status:
  = @sale.status
p
  strong Registered on:
  = @sale.registered_on
p
  strong Bank:
  = @sale.bank
p
  strong Grant amount:
  = @sale.grant_amount
p
  strong Commission amount:
  = @sale.commission_amount
p
  strong Tax amount:
  = @sale.tax_amount

= render 'commissions/commission_table', commissions: @sale.commissions